### ISSUE TITLE
Display timezone on stats page

### ISSUE THREAD

**Issue by kyrias** [tommyrot/superseriousstats#10]
Would be useful to show the timezone on the stats pages, so the data is more in-context for people looking at it.

**Comment by tommyrot** [comment]
You mean as in #2 ? Otherwise there is a RFC 2822 formatted date at the bottom of every page, indicating which timezone the statistics are created in/viewed as.

**Comment by kyrias** [comment]
That sort of works, but it's not very clearly displayed, hmm.
