### ISSUE TITLE
PostgreSQL support.

### ISSUE THREAD

**Issue by Kilobyte22** [tommyrot/superseriousstats#5]
I just asked myself SSS has undocumented PostgreSQL support. The website only talks about SQLite and MySQL.
If it doesn't, how hard would it be to implement such support? Which files would have to be changed (i cannot find any database code)?

**Comment by tommyrot** [comment]
There are no undocumented features, and no postgres support. How hard it would be depends on your skill and desire to make it happen :) I suggest having a look at php PDO so you could later change db engines more easily if you so desire.

`grep -l sqlite3 *php` will give you a list of files that have "hardcoded" interaction with the db via sqlite.
