### ISSUE TITLE
tld-verification from different directory

### ISSUE THREAD

**Issue by kyrias** [tommyrot/superseriousstats#6]
Running `sss.php` from a different directory, for example when running it under cron, gives the following warning:

```
Warning: file(tlds-alpha-by-domain.txt): failed to open stream: No such file or directory in /home/kyrias/code/superseriousstats/urltools.php on line 67
```

It should probably try to open the file from the same directory as current file is in.

**Comment by tommyrot** [comment]
I'm not sure if i want to think about what you are doing for too long, i feel it can become overly complicated if you try and run sss.php from a different directory! Although things may work it wasn't a design choice to allow for this.

That said i've committed a change that should make it work for you. And others who perhaps have an odd include_path set in php.ini. Not sure why that would be the case though.

**Comment by kyrias** [comment]
What I'm doing? Essentially the exact same thing as is listed in the sss how-to. Anyway, thanks I'll try it when I get home.

**Comment by tommyrot** [comment]
Maybe i misunderstood and you haven't moved sss.php to a place outside of the rest of the sss files :) I'm curious why you got the error, if the tlds file is in the same directory as urltools.php and readable. PHP by default looks in the same directory as the calling script regardless of crons path settings.

**Comment by kyrias** [comment]
No files moved, just running `sss.php` from a different working directory.

Does it really do that for things like`file` though, since it's supposed to be a path to a file, so only looking in the current directory would make more sense. Worked around it by doing

```
if (($tlds = file(__DIR__ . '/tlds-alpha-by-domain.txt')) === false) {
```

instead of

```
if (($tlds = file('tlds-alpha-by-domain.txt')) === false) {
```

**Comment by tommyrot** [comment]
This is now in the tree.
