### ISSUE TITLE
Multiple dates in same file

### ISSUE THREAD

**Issue by kyrias** [tommyrot/superseriousstats#7]
I wanted to write a parser for WeeChat log files, but by default it stores the the full logs in a single file, but it doesn't seem to be possible, currently, to write an sss parser for this case. How much work do you think it would be to implement?

**Comment by tommyrot** [comment]
This a very complicated issue to handle properly. I've had various reasons not to got the route of multiple dates per log, or just one big log file. My design has been one date per logfile so i don't have to worry about writing unnecessarily "smart" code and still get accurate results. How much work it would be to change this? It depends on the person writing the code. It can be done but personally i don't find it worth my effort, even if it was just maintaining this feature.

Every now and then i break up big logs from various sources into per day files by writing a little shell or PHP script specifically for that task. Perhaps you can do the same and have your client log per day from there on?

**Comment by kyrias** [comment]
Reason I wanted it was that I was importing a logfile stretching back to 2011, which took a few hours to split up and convert to another log format, so don't really need it anymore..
