### ISSUE TITLE
Quiet output

### ISSUE THREAD

**Issue by kyrias** [tommyrot/superseriousstats#8]
While running sss under cron it would be useful if it was possible to only make it print on errors, so that an email with the stdout only will be sent if there's any problems running sss.

**Comment by tommyrot** [comment]
Have you tried outputbits = "0" in sss.conf? That should only print events that make the program abort. If you want PHP to shutup if it sees issues with the code you can change error_reporting from -1 to 0 on line 8 in sss.php. These are generally the issues i would like to be aware of so i can better my code (if it hasn't been altered by others ofcourse).

**Comment by kyrias** [comment]
Would be nicer to have a commandline option for it, so that I don't have to have separate configs for cron and running it manually, but it'll work for now.
