### ISSUE TITLE
[question] Any way to force registered nick?

### ISSUE THREAD

**Issue by kyrias** [tommyrot/superseriousstats#9]
Some people in my channels have changed their primary nicks, so I'd like to force the displayed nick for these users to be the new ones, but I can't see any way to do so. Is this currently possible at all?

**Comment by tommyrot** [comment]
Out of all the linked nicks for a user, the one with the most lines will be displayed. There is no way to choose.

**Comment by tommyrot** [comment]
Ok, i think the way it is currently - where the linked nick with the most lines automatically becomes the main nick - makes the most sense. If i always chat with Bob but on the stats page he's displayed as Jack that would be confusing. I won't change this behaviour.

**Comment by kyrias** [comment]
And the point is that with a few years worth of stats, when someone changed nicks 2 years ago and has been using it constantly since, and it still shows the old nick, that most in the channel don't even know, is much more confusing.

**Comment by tommyrot** [comment]
I think this is a uncommon situation. In the past the most active nick didn't become the main nick. But like i said, i felt that it made sense to do so and i removed the option to toggle behaviour (both applied globally). In a situation like yours you would want to _selectively_ toggle the behaviour. I don't think it warrants the extra complexity it would require.
